### ISSUE TITLE
Just seeking clarification, this circumvents the "Waiting in Line" and "Verify Account" process?

### ISSUE THREAD

**Issue by norquisd** [Dogey11/B3#1]
Looking through the script, it looks like it after clicking "add to cart" the script goes directly to checkout logic. I thought there was some queue and account verification process that happened. Please let me know if I am mistaken or if this does circumvent this.

**Comment by 1404er** [comment]
At one point BestBuy did have a verification process for items marked as "popular" however I can't seem to find any mention
of this anywhere on the site. BestBuy **does** require a phone/email verification code for the first time sign in though, which is why running verify.py during the install requests the login as seen between lines 55 - 62:
```
signInBtn = driver.find_element(By.XPATH, "//*[text()='Sign In']")
            signInBtn.click()

            enterCVV = WebDriverWait(driver, 1000).until(
                presence_of_element_located((By.ID, "cvv"))
            )

            enterCVV.send_keys(000)
```
(driver, 1000) means a 1000 second wait before timing out to give the user time to enter in the verification code. AFAIK this
is the only time the code is required, meaning main.py can directly go to checkout without any confirmation.

**I am working on completely rewriting this project from scratch, using a faster api and a GUI interface. It will be a aio tool
combined with a in stock alert & web scraping features. you also wont need to install chromedriver or chrome.**

**Comment by norquisd** [comment]
Best Buy still very much introduces a queue for "popular" items. When they are in stock, you can see some text next to the item denoting that the item is popular and they expect it to sell out quick. 

When you click "add to cart" on such an item, it makes you "wait in line" and then eventually you have to "Verify your account" by clicking a button of the same name once it appears. Then it checks stores near you for availability and only after you select one with availability will you be able to add to your cart. 

At least, this is my understanding from some limited experience trying to get a card. But I do think the process is different than the scenario your verify.py script tests.

**Comment by 1404er** [comment]
Thanks for confirming. I assumed that there was confirmation needed now as they definitely **didn't** have this when I wrote the original script 9ish months ago. I'll tinker around with this a bit more as I haven't actually tried it since.
